import Link from "next/link"
import { ArrowRight, ArrowUpRight, CheckCircle, Monitor, ShoppingCart, Smartphone, Gauge } from "lucide-react"
import { Button } from "@/components/ui/button"

const services = [
  [Monitor, "Business websites", "Clear, confident websites that make your business easy to understand and easy to choose."],
  [ShoppingCart, "E-commerce", "Thoughtful online stores with less friction between the first click and the final order."],
  [Smartphone, "Responsive design", "A considered experience that works beautifully across every screen and every context."],
  [Gauge, "Optimisation", "Sharper structure, faster pages and smarter journeys for websites that have outgrown themselves."],
]

export default function WebDesignService() {
  return (
    <main className="overflow-hidden bg-background">
      <section className="relative bg-foreground px-6 py-24 text-background md:px-12 md:py-36"><div className="absolute right-0 top-0 h-full w-1/3 bg-primary [clip-path:polygon(38%_0,100%_0,100%_100%,0_100%)]" /><div className="container relative z-10"><p className="mb-8 font-mono text-xs uppercase tracking-[0.35em] text-accent">Services / Web design</p><h1 className="max-w-5xl text-6xl font-black leading-[0.88] tracking-[-0.07em] md:text-8xl lg:text-[9rem]">Websites with<br /><span className="text-primary">somewhere to go.</span></h1><div className="mt-12 flex flex-col gap-8 md:flex-row md:items-end md:justify-between"><p className="max-w-xl text-lg leading-relaxed text-background/70 md:text-xl">Beautiful, useful digital experiences for businesses ready to be taken seriously online.</p><Button asChild size="lg"><Link href="/contact">Get a free quote <ArrowUpRight data-icon="inline-end" /></Link></Button></div></div></section>
      <section className="bg-secondary px-6 py-20 md:px-12 md:py-32"><div className="container"><div className="mb-16 grid gap-6 lg:grid-cols-[1fr_0.6fr]"><div><p className="mb-5 font-mono text-xs uppercase tracking-[0.3em] text-primary">What we make</p><h2 className="max-w-3xl text-5xl font-black leading-none tracking-[-0.06em] md:text-7xl">Not just a nice<br /><span className="text-primary">looking website.</span></h2></div><p className="self-end text-lg leading-relaxed text-muted-foreground">Every project starts with the same question: what needs to happen next? The answer shapes the strategy, the story and the interface.</p></div><div className="grid gap-px bg-border md:grid-cols-2">{services.map(([Icon, title, text], index) => <article key={title as string} className={`min-h-72 p-8 ${index % 2 === 0 ? "bg-background" : "bg-primary text-primary-foreground"}`}><Icon className="mb-16 size-8" /><p className="mb-3 font-mono text-xs opacity-60">0{index + 1}</p><h3 className="mb-3 text-3xl font-bold">{title as string}</h3><p className="max-w-sm leading-relaxed opacity-75">{text as string}</p></article>)}</div></div></section>
      <section className="px-6 py-20 md:px-12 md:py-32"><div className="container grid gap-16 lg:grid-cols-[0.8fr_1.2fr]"><div><p className="mb-5 font-mono text-xs uppercase tracking-[0.3em] text-accent">The process</p><h2 className="text-5xl font-black leading-none tracking-[-0.06em] md:text-7xl">Clear steps.<br /><span className="text-primary">No fog.</span></h2></div><div className="grid gap-6">{["Discovery — understand the opportunity", "Direction — find the sharpest idea", "Design — make the experience feel right", "Launch — put it to work and keep improving"].map((step, index) => <div key={step} className="flex items-center gap-6 border-b border-border pb-6"><span className="font-mono text-sm text-primary">0{index + 1}</span><span className="text-xl font-medium">{step}</span><CheckCircle className="ml-auto size-5 text-accent" /></div>)}</div></div></section>
      <section className="bg-primary px-6 py-20 text-primary-foreground md:px-12 md:py-28"><div className="container flex flex-col justify-between gap-8 md:flex-row md:items-end"><h2 className="max-w-3xl text-5xl font-black leading-none tracking-[-0.06em] md:text-7xl">Ready to make a better first impression?</h2><Link href="/contact" className="inline-flex items-center gap-3 border border-primary-foreground/40 px-6 py-4 font-mono text-xs uppercase tracking-[0.2em] transition hover:bg-primary-foreground hover:text-primary">Let&apos;s talk <ArrowRight className="size-5" /></Link></div></section>
    </main>
  )
}
