import Link from "next/link"
import { ArrowDown, ArrowUpRight } from "lucide-react"
import { groupServices, serviceGroups } from "@/lib/services"

export const metadata = { title: "Services", description: "Digital experiences built to perform: websites, growth and ongoing support from Dream Pixel in Devon." }

export default function ServicesPage() {
  return <main className="overflow-hidden bg-background">
    <section className="relative min-h-[78vh] overflow-hidden bg-foreground px-6 py-28 text-background md:px-12 md:py-40">
      <div className="pointer-events-none absolute right-[-12%] top-[-20%] size-[68vw] rounded-full border border-primary/25" />
      <div className="pointer-events-none absolute bottom-10 right-10 size-3 bg-accent shadow-[0_0_0_14px_hsl(var(--accent)/.12)]" />
      <div className="container relative z-10"><p className="mb-8 font-mono text-xs uppercase tracking-[.35em] text-accent">What we do / Services</p><h1 className="max-w-6xl font-display text-6xl font-black leading-[.86] tracking-[-.07em] md:text-8xl lg:text-[9.5rem]">Digital experiences<br /><span className="text-primary">built to perform.</span></h1><div className="mt-12 flex max-w-4xl flex-col justify-between gap-8 border-t border-background/20 pt-6 md:flex-row md:items-end"><p className="max-w-xl text-lg leading-relaxed text-background/70 md:text-xl">We design, build and grow high-performance websites for ambitious businesses across Devon and beyond.</p><div className="flex flex-wrap gap-3"><Link href="/contact" className="inline-flex items-center gap-3 bg-primary px-5 py-4 font-mono text-xs uppercase tracking-[.18em] text-primary-foreground transition hover:bg-accent">Start a project <ArrowUpRight className="size-4" /></Link><Link href="/portfolio" className="inline-flex items-center gap-3 border border-background/30 px-5 py-4 font-mono text-xs uppercase tracking-[.18em] transition hover:border-background hover:bg-background hover:text-foreground">View our work</Link></div></div></div>
    </section>
    <section className="bg-background px-6 py-24 md:px-12 md:py-36"><div className="container"><div className="mb-20 max-w-2xl"><p className="mb-5 font-mono text-xs uppercase tracking-[.3em] text-primary">One connected studio</p><h2 className="font-display text-5xl font-black leading-[.9] tracking-[-.06em] md:text-7xl">Strategy + design + technology + growth.</h2></div><div className="flex flex-col gap-px bg-border">{serviceGroups.map((group) => <section key={group.name} className="bg-card px-6 py-12 md:px-10 md:py-16"><div className="grid gap-10 lg:grid-cols-[.75fr_1.25fr]"><div><p className="font-mono text-xs uppercase tracking-[.3em] text-accent">{group.number} / {group.name}</p><h2 className="mt-8 max-w-xl font-display text-4xl font-black leading-[.92] tracking-[-.05em] md:text-6xl">{group.title}</h2><p className="mt-6 max-w-md leading-relaxed text-muted-foreground">{group.intro}</p></div><div className="grid gap-3 sm:grid-cols-2">{groupServices(group.name).map((service) => <Link key={service.slug} href={`/services/${service.slug}`} className="group/link flex min-h-36 flex-col justify-between border border-border p-5 transition hover:border-primary hover:bg-primary hover:text-primary-foreground"><span className="font-mono text-xs uppercase tracking-[.18em] text-primary group-hover/link:text-primary-foreground">{service.eyebrow}</span><span className="flex items-end justify-between gap-3 text-xl font-semibold">{service.shortTitle}<ArrowUpRight className="size-5 shrink-0 transition group-hover/link:translate-x-1 group-hover/link:-translate-y-1" /></span></Link>)}</div></div></section>)}</div></div></section>
    <section className="bg-primary px-6 py-24 text-primary-foreground md:px-12 md:py-32"><div className="container flex flex-col justify-between gap-10 md:flex-row md:items-end"><div><p className="mb-5 font-mono text-xs uppercase tracking-[.3em] text-primary-foreground/70">No one-size-fits-all</p><h2 className="max-w-4xl font-display text-5xl font-black leading-[.9] tracking-[-.06em] md:text-8xl">The right work,<br />in the right order.</h2></div><Link href="/contact" className="inline-flex items-center gap-3 border border-primary-foreground/40 px-6 py-4 font-mono text-xs uppercase tracking-[.18em] transition hover:bg-primary-foreground hover:text-primary">Talk through your project <ArrowUpRight className="size-5" /></Link></div></section>
  </main>
}
