import type { Location } from "@/lib/locations"
import Link from "next/link"
import Image from "next/image"
import { ArrowUpRight, Check } from "lucide-react"

export function LocationPage({ location }: { location: Location }) {
  const pageUrl = `https://dreampixel.co.uk/web-design-${location.slug}`
  const structuredData = { "@context": "https://schema.org", "@type": "ProfessionalService", name: `Dream Pixel Web Design ${location.name}`, url: pageUrl, image: `https://dreampixel.co.uk${location.image}`, areaServed: { "@type": "City", name: location.name, containedInPlace: { "@type": "AdministrativeArea", name: location.region } }, serviceType: "Web design and website development", provider: { "@type": "LocalBusiness", name: "Dream Pixel", url: "https://dreampixel.co.uk" } }
  return <main className="overflow-hidden bg-background"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(structuredData) }} />
    <section className="relative border-b border-border px-6 py-24 md:px-12 md:py-36">
      <div className="container grid gap-14 lg:grid-cols-[1fr_.85fr] lg:items-end">
        <div><p className="mb-7 font-mono text-xs uppercase tracking-[.3em] text-accent">Web design / {location.region}</p><h1 className="max-w-5xl font-display text-6xl font-black leading-[.86] tracking-[-.07em] md:text-8xl lg:text-[8.5rem]">Web design<br /><span className="text-primary">in {location.name}.</span></h1><p className="mt-8 max-w-xl text-lg leading-relaxed text-muted-foreground md:text-xl">{location.intro}</p><div className="mt-9 flex flex-wrap gap-3"><Link href="/contact" className="inline-flex items-center gap-3 bg-primary px-5 py-4 font-mono text-xs uppercase tracking-[.18em] text-primary-foreground transition hover:bg-accent">Start a project <ArrowUpRight className="size-4" /></Link><Link href="/portfolio" className="inline-flex items-center gap-3 border border-border px-5 py-4 font-mono text-xs uppercase tracking-[.18em] transition hover:border-primary hover:text-primary">View our work</Link></div></div>
        <div className="relative aspect-[4/3] overflow-hidden border border-border bg-card"><Image src={location.image} alt={location.imageAlt} fill priority className="object-cover" sizes="(min-width: 1024px) 42vw, 100vw" /><div className="absolute inset-0 bg-gradient-to-t from-background/65 to-transparent" /><p className="absolute bottom-5 left-5 font-mono text-xs uppercase tracking-[.2em] text-foreground">{location.name} / {location.region}</p></div>
      </div>
    </section>
    <section className="border-b border-border bg-card px-6 py-20 md:px-12 md:py-28"><div className="container grid gap-12 lg:grid-cols-[.7fr_1.3fr]"><div><p className="font-mono text-xs uppercase tracking-[.3em] text-primary">Local perspective</p><h2 className="mt-6 max-w-lg font-display text-5xl font-black leading-[.9] tracking-[-.06em] md:text-7xl">Built for the place you do business.</h2></div><div><p className="max-w-2xl text-lg leading-relaxed text-muted-foreground">{location.localContext}</p><p className="mt-6 max-w-2xl leading-relaxed text-muted-foreground">We do not use location pages as empty doorway pages. We use local context to make the page genuinely useful, then connect it to the strategy, design and search work your business actually needs.</p><div className="mt-10 flex flex-wrap gap-2">{location.nearby.map((area) => <span key={area} className="border border-border px-3 py-2 font-mono text-xs uppercase tracking-[.14em] text-muted-foreground">{area}</span>)}</div></div></div></section>
    <section className="px-6 py-20 md:px-12 md:py-28"><div className="container grid gap-12 lg:grid-cols-[.7fr_1.3fr]"><div><p className="font-mono text-xs uppercase tracking-[.3em] text-primary">A local digital partner</p><h2 className="mt-6 max-w-lg font-display text-5xl font-black leading-[.9] tracking-[-.06em]">Web design with a reason behind it.</h2></div><div className="space-y-6 text-lg leading-relaxed text-muted-foreground"><p>{location.audience ?? `We work with businesses in ${location.name} that need a website to explain their value, build trust and generate better enquiries.`}</p><p>{location.approach ?? `Our process brings strategy, content, design, development and search visibility together, so the website works as one useful business tool rather than a collection of disconnected pages.`}</p><p>That means asking better questions before the design begins, making the important information easy to find, and building a site that is fast, accessible and straightforward to improve over time.</p></div></div></section>
    <section className="px-6 py-20 md:px-12 md:py-28"><div className="container"><div className="mb-12 flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><p className="font-mono text-xs uppercase tracking-[.3em] text-accent">What we can help with</p><h2 className="mt-5 font-display text-5xl font-black leading-[.9] tracking-[-.06em] md:text-7xl">A website that<br /><span className="text-primary">does its job.</span></h2></div><Link href="/services" className="link-arrow text-sm font-semibold">Explore all services <ArrowUpRight className="size-4" /></Link></div><div className="grid gap-px bg-border md:grid-cols-3">{location.focus.map((item, index) => <Link href={index === 0 ? "/services/web-design" : index === 1 ? "/services/website-development" : "/services/local-seo"} key={item} className="group bg-card p-6 transition hover:bg-primary hover:text-primary-foreground"><span className="font-mono text-xs text-accent group-hover:text-primary-foreground">0{index + 1}</span><h3 className="mt-16 text-2xl font-semibold">{item}</h3><span className="mt-8 flex items-center gap-2 text-sm text-muted-foreground group-hover:text-primary-foreground">See how we help <ArrowUpRight className="size-4 transition group-hover:translate-x-1 group-hover:-translate-y-1" /></span></Link>)}</div></div></section>
    <section className="bg-card px-6 py-20 md:px-12 md:py-28"><div className="container grid gap-12 lg:grid-cols-2"><div><p className="font-mono text-xs uppercase tracking-[.3em] text-accent">What makes the difference</p><h2 className="mt-6 max-w-xl font-display text-5xl font-black leading-[.9] tracking-[-.06em]">A site that works beyond the first impression.</h2></div><div className="space-y-6 text-muted-foreground"><p className="text-lg leading-relaxed">Good local web design is not just putting a town name into a page title. It is understanding the questions customers ask, the alternatives they compare, and the evidence they need before they contact you.</p><p className="leading-relaxed">We build that usefulness into the structure: clear service pages, concise calls to action, relevant project evidence, accessible content and technical foundations that support search without compromising the reader’s experience.</p><p className="leading-relaxed">For businesses serving more than one area, we create a sensible relationship between the main service page, local pages and supporting insights. That helps people move from a broad search to the specific answer they need.</p></div></div></section>
    <section className="bg-primary px-6 py-20 text-primary-foreground md:px-12 md:py-28"><div className="container flex flex-col justify-between gap-10 md:flex-row md:items-end"><div><p className="font-mono text-xs uppercase tracking-[.3em] text-primary-foreground/70">{location.name} / Devon / UK</p><h2 className="mt-5 max-w-4xl font-display text-5xl font-black leading-[.9] tracking-[-.06em] md:text-8xl">Let&apos;s make your<br />next step clearer.</h2></div><Link href="/contact" className="inline-flex items-center gap-3 border border-primary-foreground/40 px-6 py-4 font-mono text-xs uppercase tracking-[.18em] transition hover:bg-primary-foreground hover:text-primary">Talk through your project <ArrowUpRight className="size-5" /></Link></div></section>
  </main>
}
