export type GlossaryCategory = "SEO" | "Web Design & UX" | "Web Development" | "E-commerce" | "Digital Marketing"

export type GlossaryTerm = {
  slug: string
  term: string
  category: GlossaryCategory
  definition: string
  whyItMatters: string
  example?: string
  related: string[]
  service?: { label: string; href: string }
  insight?: { label: string; href: string }
}

export const glossaryCategories: GlossaryCategory[] = ["SEO", "Web Design & UX", "Web Development", "E-commerce", "Digital Marketing"]

export const glossaryTerms: GlossaryTerm[] = [
  { slug: "seo", term: "SEO", category: "SEO", definition: "Search engine optimisation is the practical work of making a website easier for search engines to understand and easier for the right people to find.", whyItMatters: "Good SEO connects your expertise with people who are already looking for the thing you do. It is a mix of useful content, technical clarity and consistency rather than a shortcut to instant rankings.", example: "A local photographer might optimise a service page around the questions couples ask before booking a wedding photographer.", related: ["local-seo", "search-intent", "organic-traffic", "technical-seo"], service: { label: "Explore SEO", href: "/services/seo" }, insight: { label: "Read our SEO insight", href: "/insights/seo" } },
  { slug: "local-seo", term: "Local SEO", category: "SEO", definition: "Local SEO helps a business appear when people search for a product or service in a particular place.", whyItMatters: "People often choose from a short list of nearby businesses. Consistent business information, useful local pages, reviews and genuine relevance help you make that shortlist.", related: ["seo", "search-visibility", "organic-traffic", "structured-data"], service: { label: "Explore Local SEO", href: "/services/local-seo" } },
  { slug: "technical-seo", term: "Technical SEO", category: "SEO", definition: "Technical SEO is the work that helps search engines crawl, understand and index your website effectively.", whyItMatters: "A beautifully designed website is of limited value if search engines cannot properly access its important content. Technical checks also tend to improve the experience for real people.", example: "Reviewing broken links, page speed, redirects, canonical URLs and mobile behaviour is part of a technical SEO review.", related: ["crawlability", "indexation", "canonical-url", "sitemap", "core-web-vitals"], service: { label: "Explore Technical SEO", href: "/services/technical-seo" } },
  { slug: "keyword-research", term: "Keyword research", category: "SEO", definition: "Keyword research is the process of understanding the words and questions people use when they search for something.", whyItMatters: "It helps a business choose language that matches real demand without forcing awkward phrases into its content. The best research considers the reason behind a search, not just its volume.", related: ["search-intent", "serp", "on-page-seo", "internal-linking"], service: { label: "Explore SEO", href: "/services/seo" }, insight: { label: "Read the SEO insight", href: "/insights/seo" } },
  { slug: "search-intent", term: "Search intent", category: "SEO", definition: "Search intent is what someone is actually trying to achieve when they type a query into a search engine.", whyItMatters: "A page can use the right words and still be unhelpful if it answers the wrong question. Matching intent makes content more useful and usually makes the next step clearer.", example: "Someone searching ‘how to choose a web designer’ needs guidance, while someone searching ‘web design Devon’ may be ready to compare providers.", related: ["keyword-research", "serp", "landing-page", "conversion-rate-optimisation"] },
  { slug: "serp", term: "SERP", category: "SEO", definition: "SERP stands for search engine results page: the page shown after someone searches for something.", whyItMatters: "Looking at the results for a query helps you understand what searchers expect, which competitors appear and what kind of page could genuinely add value.", related: ["search-intent", "organic-traffic", "search-visibility", "meta-title"] },
  { slug: "organic-traffic", term: "Organic traffic", category: "SEO", definition: "Organic traffic is the people who reach your website through unpaid search engine results.", whyItMatters: "Organic visibility can create a steady source of relevant visits, but it needs useful content and a sound technical foundation to keep earning attention.", related: ["seo", "search-visibility", "paid-traffic", "analytics"], service: { label: "Explore SEO", href: "/services/seo" } },
  { slug: "search-visibility", term: "Search visibility", category: "SEO", definition: "Search visibility is a broad view of how often and how prominently a website appears for relevant searches.", whyItMatters: "It is more useful than focusing on one ranking in isolation because it shows whether your overall presence is becoming easier to find.", related: ["organic-traffic", "serp", "keyword-research", "local-seo"] },
  { slug: "crawlability", term: "Crawlability", category: "SEO", definition: "Crawlability describes how easily search engine crawlers can discover and move through a website.", whyItMatters: "If important pages are blocked, disconnected or difficult to reach, search engines may not discover the work you have put into them.", related: ["indexation", "robots-txt", "sitemap", "internal-linking"], service: { label: "Explore Technical SEO", href: "/services/technical-seo" } },
  { slug: "indexation", term: "Indexation", category: "SEO", definition: "Indexation is the process of a search engine storing and considering a page for inclusion in its results.", whyItMatters: "A page cannot earn organic visibility if it is not eligible to appear. Indexation checks help separate a content problem from an access or configuration problem.", related: ["crawlability", "robots-txt", "canonical-url", "sitemap"], service: { label: "Explore Technical SEO", href: "/services/technical-seo" } },
  { slug: "sitemap", term: "Sitemap", category: "SEO", definition: "A sitemap is a file that gives search engines a structured list of the important URLs on a website.", whyItMatters: "It can help crawlers discover content, particularly on larger or recently changed websites, although it does not guarantee indexing.", related: ["crawlability", "indexation", "robots-txt", "canonical-url"] },
  { slug: "robots-txt", term: "Robots.txt", category: "SEO", definition: "Robots.txt is a small file that gives automated crawlers instructions about which areas of a website they may request.", whyItMatters: "A carefully managed file can reduce unnecessary crawling. A mistake can also make important content harder for search engines to access, so it needs to be handled with care.", related: ["crawlability", "indexation", "sitemap", "technical-seo"] },
  { slug: "canonical-url", term: "Canonical URL", category: "SEO", definition: "A canonical URL tells search engines which version of similar or duplicated pages should be treated as the main one.", whyItMatters: "It helps clarify preferred URLs when content is reachable through more than one address, such as filtered catalogue pages or tracking variations.", related: ["indexation", "301-redirect", "sitemap", "technical-seo"] },
  { slug: "301-redirect", term: "301 redirect", category: "SEO", definition: "A 301 redirect sends visitors and crawlers from an old URL to a new, permanent address.", whyItMatters: "Redirects are essential when pages move or a website is redesigned. A thoughtful redirect plan helps people find what they expected and protects useful search signals.", related: ["canonical-url", "website-migration", "http-status-codes"], service: { label: "Explore website redesign", href: "/services/website-redesign" } },
  { slug: "backlinks", term: "Backlinks", category: "SEO", definition: "Backlinks are links from other websites to yours.", whyItMatters: "Relevant, editorially earned links can help people discover your content and can contribute to how search engines understand its reputation. More is not always better.", related: ["domain-authority", "digital-pr", "anchor-text"], service: { label: "Explore Digital PR", href: "/services/digital-pr" } },
  { slug: "structured-data", term: "Structured data", category: "SEO", definition: "Structured data is machine-readable information added to a page to clarify what its content represents.", whyItMatters: "It can help search engines interpret details such as an organisation, article, service or product. It should describe the page accurately, not promise a search feature.", related: ["schema-markup", "product-schema", "technical-seo"] },
  { slug: "core-web-vitals", term: "Core Web Vitals", category: "SEO", definition: "Core Web Vitals are a set of user-focused measurements covering loading performance, responsiveness and visual stability.", whyItMatters: "They turn vague complaints about a slow or jumpy website into signals a team can investigate. Improving them usually benefits visitors as well as search visibility.", related: ["website-performance", "responsive-web-design", "technical-seo"], service: { label: "Explore Technical SEO", href: "/services/technical-seo" } },
  { slug: "meta-title", term: "Meta title", category: "SEO", definition: "A meta title is the page title commonly used by search engines as a clickable result heading.", whyItMatters: "A clear, accurate title helps someone decide whether a result is relevant before they visit. It should describe the page rather than repeat a keyword unnaturally.", related: ["meta-description", "serp", "on-page-seo"] },
  { slug: "meta-description", term: "Meta description", category: "SEO", definition: "A meta description is a short summary that may appear beneath a page title in search results.", whyItMatters: "It gives searchers useful context and can make the purpose of a page clearer, even though search engines may choose a different snippet.", related: ["meta-title", "serp", "search-intent"] },
  { slug: "alt-text", term: "Alt text", category: "SEO", definition: "Alt text is a concise written description of an image for people who cannot see it and for situations where the image is unavailable.", whyItMatters: "Good alt text supports accessible browsing and gives search engines context. Decorative images should usually have empty alt text rather than a made-up description.", related: ["accessibility", "on-page-seo", "usability"] },
  { slug: "internal-linking", term: "Internal linking", category: "SEO", definition: "Internal links connect pages within the same website.", whyItMatters: "They help people move to the next useful piece of information and help search engines understand how pages relate to one another.", related: ["crawlability", "information-architecture", "anchor-text"] },
  { slug: "e-e-a-t", term: "E-E-A-T", category: "SEO", definition: "E-E-A-T stands for experience, expertise, authoritativeness and trustworthiness: qualities search systems look for when assessing useful content.", whyItMatters: "It is a useful lens for making content more credible and grounded in real experience. It is not a score you can simply add to a page.", related: ["content-marketing", "digital-pr", "search-intent"] },
  { slug: "ux", term: "UX", category: "Web Design & UX", definition: "UX means user experience: the way a person understands, navigates and feels while using a website or product.", whyItMatters: "A strong visual style cannot compensate for a confusing journey. UX work makes the important actions easier to understand and complete.", example: "Clarifying a service page, reducing form friction and making mobile navigation predictable are all UX improvements.", related: ["ui", "user-journey", "usability", "conversion-rate-optimisation"], service: { label: "Explore web design", href: "/services/web-design" } },
  { slug: "ui", term: "UI", category: "Web Design & UX", definition: "UI means user interface: the visual and interactive elements people use to operate a website or product.", whyItMatters: "Typography, spacing, colour, controls and feedback all affect whether an experience feels clear and trustworthy.", related: ["ux", "design-system", "interaction-design", "accessibility"], service: { label: "Explore web design", href: "/services/web-design" } },
  { slug: "responsive-web-design", term: "Responsive web design", category: "Web Design & UX", definition: "Responsive web design creates layouts that adapt to different screen sizes, input methods and device contexts.", whyItMatters: "People do not experience your website in one standard viewport. A responsive site keeps content legible and actions usable from a phone to a large desktop.", related: ["mobile-first-design", "usability", "website-performance"], service: { label: "Explore web design", href: "/services/web-design" } },
  { slug: "mobile-first-design", term: "Mobile-first design", category: "Web Design & UX", definition: "Mobile-first design starts by solving the constraints of a small screen before expanding the experience for larger screens.", whyItMatters: "It forces a team to prioritise the content and actions that matter, rather than hiding a desktop layout inside a smaller viewport.", related: ["responsive-web-design", "ux", "accessibility"] },
  { slug: "information-architecture", term: "Information architecture", category: "Web Design & UX", definition: "Information architecture is the structure and labelling system that helps people find their way through content.", whyItMatters: "Clear navigation is not decoration. It reduces the effort needed to understand what a business offers and where to go next.", related: ["user-journey", "wireframe", "internal-linking"], service: { label: "Explore web design", href: "/services/web-design" } },
  { slug: "user-journey", term: "User journey", category: "Web Design & UX", definition: "A user journey maps the steps, questions and decisions someone moves through while trying to achieve something.", whyItMatters: "Seeing the whole route reveals gaps between landing on a page and taking action, including moments where people need more proof or clarity.", related: ["ux", "information-architecture", "landing-page", "conversion-rate-optimisation"] },
  { slug: "wireframe", term: "Wireframe", category: "Web Design & UX", definition: "A wireframe is a simplified layout that explores structure, content priority and interaction before visual polish is added.", whyItMatters: "It is cheaper to solve a confusing layout in a wireframe than after development. Wireframes keep early conversations focused on purpose.", related: ["prototype", "information-architecture", "design-system"] },
  { slug: "prototype", term: "Prototype", category: "Web Design & UX", definition: "A prototype is an interactive representation of a product or page used to explore how it behaves before it is built.", whyItMatters: "Prototypes let teams test a journey, explain a concept and find issues while changes are still relatively easy.", related: ["wireframe", "ux", "interaction-design"] },
  { slug: "design-system", term: "Design system", category: "Web Design & UX", definition: "A design system is a shared set of visual rules, components and guidance for creating a consistent digital experience.", whyItMatters: "It helps a website stay coherent as more pages and features are added, while reducing repeated design and development work.", related: ["ui", "accessibility", "responsive-web-design"], service: { label: "Explore web design", href: "/services/web-design" } },
  { slug: "conversion-rate-optimisation", term: "Conversion rate optimisation", category: "Web Design & UX", definition: "Conversion rate optimisation, or CRO, is the process of improving a digital journey so more of the right visitors complete a valuable action.", whyItMatters: "It focuses attention on whether a website is helping the business, not just whether people arrive. Useful CRO starts with evidence and clear user needs.", related: ["cta", "user-journey", "analytics", "landing-page"], service: { label: "Explore web design", href: "/services/web-design" } },
  { slug: "cta", term: "CTA", category: "Web Design & UX", definition: "A CTA, or call to action, is a prompt that invites someone to take the next step.", whyItMatters: "Clear calls to action reduce uncertainty. The best one describes a useful next step rather than shouting for attention.", example: "‘View the work’ and ‘Tell us about your project’ are more informative than a generic ‘Click here’.", related: ["landing-page", "conversion-rate-optimisation", "user-journey"] },
  { slug: "above-the-fold", term: "Above the fold", category: "Web Design & UX", definition: "Above the fold refers to the part of a page visible before someone scrolls.", whyItMatters: "It should establish relevance and provide a clear route onwards, but it does not need to contain everything. Good pages reward scrolling.", related: ["landing-page", "cta", "responsive-web-design"] },
  { slug: "accessibility", term: "Accessibility", category: "Web Design & UX", definition: "Accessibility means designing and building digital experiences that can be used by people with a wide range of abilities and assistive technologies.", whyItMatters: "Accessible websites are more inclusive and often clearer for everyone. Keyboard access, readable contrast, meaningful labels and sensible structure are practical foundations.", related: ["usability", "alt-text", "responsive-web-design", "ui"] },
  { slug: "usability", term: "Usability", category: "Web Design & UX", definition: "Usability describes how easily people can understand and use a website to achieve what they came to do.", whyItMatters: "A usable website makes fewer demands on attention and memory. That builds confidence and reduces avoidable drop-off.", related: ["ux", "accessibility", "user-journey"] },
  { slug: "html", term: "HTML", category: "Web Development", definition: "HTML is the markup language that gives web content its structure and meaning.", whyItMatters: "Headings, links, lists, forms and landmarks give people and machines a reliable way to understand a page. Good HTML is an accessibility and SEO foundation.", related: ["css", "javascript", "accessibility", "server-side-rendering"] },
  { slug: "css", term: "CSS", category: "Web Development", definition: "CSS is the language used to control the presentation and layout of web pages.", whyItMatters: "It handles things such as typography, spacing, colour, responsive layouts and states without mixing visual rules into the content structure.", related: ["html", "responsive-web-design", "design-system"] },
  { slug: "javascript", term: "JavaScript", category: "Web Development", definition: "JavaScript is a programming language used to add behaviour and interactivity to websites.", whyItMatters: "It can make an interface feel immediate and useful, but it should enhance a solid HTML experience rather than become a requirement for basic content.", related: ["html", "client-side-rendering", "api"] },
  { slug: "front-end", term: "Front-end", category: "Web Development", definition: "Front-end development is the part of building a website that runs in the browser and creates the interface people use.", whyItMatters: "Good front-end work turns design into a fast, responsive and accessible experience across real devices.", related: ["html", "css", "javascript", "website-performance"], service: { label: "Explore website development", href: "/services/website-development" } },
  { slug: "back-end", term: "Back-end", category: "Web Development", definition: "Back-end development covers the server-side logic, data and integrations that support a website or digital product.", whyItMatters: "The back end handles the work users do not see, such as processing forms, retrieving content and connecting services securely.", related: ["api", "cms", "server-side-rendering"], service: { label: "Explore website development", href: "/services/website-development" } },
  { slug: "cms", term: "CMS", category: "Web Development", definition: "A CMS, or content management system, lets people create and maintain website content through an editing interface.", whyItMatters: "The right CMS gives a team control without forcing them to understand the underlying code. The best choice depends on content, workflow and budget.", related: ["headless-cms", "website-migration", "information-architecture"], service: { label: "Explore website development", href: "/services/website-development" } },
  { slug: "api", term: "API", category: "Web Development", definition: "An API is a defined way for different software systems to exchange data or request actions.", whyItMatters: "APIs allow websites to connect with tools such as payments, booking systems, CRMs, stock platforms and search services without rebuilding everything in one place.", related: ["back-end", "cms", "e-commerce"] },
  { slug: "hosting", term: "Hosting", category: "Web Development", definition: "Hosting is the service and infrastructure that stores a website and makes it available on the internet.", whyItMatters: "Hosting affects reliability, speed, security, deployment and how easily a website can grow. It is part of the product, not an afterthought.", related: ["domain", "dns", "cdn", "website-performance"] },
  { slug: "domain", term: "Domain", category: "Web Development", definition: "A domain is the human-readable address people use to reach a website, such as dreampixel.co.uk.", whyItMatters: "A clear, trusted domain makes a business easier to remember and gives the website a stable public address even when the underlying hosting changes.", related: ["dns", "ssl", "hosting"] },
  { slug: "dns", term: "DNS", category: "Web Development", definition: "DNS, or the Domain Name System, directs a domain name to the servers and services that should respond to it.", whyItMatters: "DNS sits behind website hosting, email and verification services. Small configuration mistakes can make a working website or mailbox appear unavailable.", related: ["domain", "hosting", "ssl"] },
  { slug: "ssl", term: "SSL", category: "Web Development", definition: "SSL is the common term for the encryption that protects data travelling between a browser and a website, usually shown by HTTPS.", whyItMatters: "Encryption protects visitors and is a basic expectation for trust, forms and modern web browsers.", related: ["hosting", "http", "website-performance"] },
  { slug: "cdn", term: "CDN", category: "Web Development", definition: "A CDN, or content delivery network, serves cached website files from locations closer to the people requesting them.", whyItMatters: "Serving assets closer to visitors can reduce loading time and improve resilience, particularly for sites with a distributed audience.", related: ["hosting", "website-performance", "core-web-vitals"] },
  { slug: "website-migration", term: "Website migration", category: "Web Development", definition: "A website migration is a significant change to a site’s platform, domain, structure, design or hosting.", whyItMatters: "Migrations combine technical, content and SEO risk. Planning URLs, redirects, analytics and launch checks early prevents avoidable surprises.", related: ["301-redirect", "cms", "hosting", "technical-seo"], service: { label: "Explore website redesign", href: "/services/website-redesign" } },
  { slug: "http-status-codes", term: "HTTP status codes", category: "Web Development", definition: "HTTP status codes are server responses that describe what happened when a browser or crawler requested a URL.", whyItMatters: "Codes such as 200, 301, 404 and 500 help teams diagnose broken journeys, redirects and server problems.", related: ["404", "301-redirect", "website-migration"] },
  { slug: "404", term: "404", category: "Web Development", definition: "A 404 is an HTTP response meaning the requested page could not be found at that address.", whyItMatters: "Broken links are frustrating, but a helpful 404 page can guide someone back to relevant content while the underlying URL is fixed.", related: ["http-status-codes", "301-redirect", "website-migration"] },
  { slug: "server-side-rendering", term: "Server-side rendering", category: "Web Development", definition: "Server-side rendering creates a page’s HTML on the server before sending it to the browser.", whyItMatters: "It can improve the first experience of a page and gives crawlers meaningful HTML to work with, depending on the project and data needs.", related: ["client-side-rendering", "website-performance", "html"], service: { label: "Explore website development", href: "/services/website-development" } },
  { slug: "client-side-rendering", term: "Client-side rendering", category: "Web Development", definition: "Client-side rendering uses browser JavaScript to assemble or update parts of a page after it loads.", whyItMatters: "It can create rich app-like interactions, but important content should not become inaccessible to people or crawlers when JavaScript is delayed or unavailable.", related: ["server-side-rendering", "javascript", "website-performance"] },
  { slug: "headless-cms", term: "Headless CMS", category: "Web Development", definition: "A headless CMS manages content separately from the front-end presentation layer, delivering it through an API.", whyItMatters: "This separation can support multiple channels and bespoke interfaces, but it also introduces more technical decisions than a traditional CMS.", related: ["cms", "api", "front-end", "back-end"] },
  { slug: "website-performance", term: "Website performance", category: "Web Development", definition: "Website performance is how quickly and reliably a site loads, responds and remains stable while someone uses it.", whyItMatters: "Performance affects patience, accessibility, conversion and search visibility. It is shaped by design, content, code, hosting and third-party services together.", related: ["core-web-vitals", "cdn", "responsive-web-design"], service: { label: "Explore website development", href: "/services/website-development" } },
  { slug: "e-commerce", term: "E-commerce", category: "E-commerce", definition: "E-commerce is the buying and selling of products or services through a digital storefront.", whyItMatters: "A successful store needs more than product grids. Trust, discovery, stock, payments, delivery and support all shape the customer journey.", related: ["product-page", "shopping-cart", "checkout", "e-commerce-seo"], service: { label: "Explore e-commerce", href: "/services/ecommerce" } },
  { slug: "product-page", term: "Product page", category: "E-commerce", definition: "A product page is the page where someone learns enough about an item to decide whether to buy it.", whyItMatters: "Good product pages answer practical questions, make value clear and remove uncertainty around price, options, delivery and returns.", related: ["product-schema", "conversion-rate", "customer-journey"], service: { label: "Explore e-commerce", href: "/services/ecommerce" } },
  { slug: "shopping-cart", term: "Shopping cart", category: "E-commerce", definition: "A shopping cart holds the products someone intends to purchase before checkout.", whyItMatters: "A useful cart keeps choices visible, makes changes easy and avoids surprising costs or unclear next steps.", related: ["checkout", "payment-gateway", "customer-journey"] },
  { slug: "checkout", term: "Checkout", category: "E-commerce", definition: "Checkout is the part of an online shop where someone confirms their order, provides details and pays.", whyItMatters: "Unnecessary fields, uncertainty and technical errors at checkout create expensive abandonment. Clarity and reassurance matter here more than cleverness.", related: ["shopping-cart", "payment-gateway", "conversion-rate"], service: { label: "Explore e-commerce", href: "/services/ecommerce" } },
  { slug: "payment-gateway", term: "Payment gateway", category: "E-commerce", definition: "A payment gateway securely passes payment information between a customer, a merchant and a payment provider.", whyItMatters: "The gateway is part of a wider checkout experience involving trust, supported payment methods, fraud controls and reliable order confirmation.", related: ["checkout", "api", "customer-journey"] },
  { slug: "product-schema", term: "Product schema", category: "E-commerce", definition: "Product schema is structured data that describes details such as a product’s name, price, availability and reviews in a machine-readable format.", whyItMatters: "Accurate product information can help search engines interpret a catalogue. It must match what people can actually see and buy on the page.", related: ["structured-data", "product-page", "e-commerce-seo"] },
  { slug: "e-commerce-seo", term: "E-commerce SEO", category: "E-commerce", definition: "E-commerce SEO helps product and category pages appear for searches made by people looking to explore or buy.", whyItMatters: "It combines technical foundations with useful product information, sensible catalogue structure and a clear understanding of how people compare options.", related: ["product-page", "product-schema", "seo"], service: { label: "Explore e-commerce", href: "/services/ecommerce" } },
  { slug: "conversion-rate", term: "Conversion rate", category: "E-commerce", definition: "Conversion rate is the percentage of people who complete a defined action from the people who had the opportunity to do it.", whyItMatters: "It gives a useful way to assess a journey, but the percentage needs context. More conversions are not automatically better if quality or customer fit falls.", related: ["conversion-rate-optimisation", "analytics", "checkout"] },
  { slug: "product-feed", term: "Product feed", category: "E-commerce", definition: "A product feed is a structured file or connection that sends catalogue information to another service, such as an advertising or shopping platform.", whyItMatters: "Accurate feeds keep product names, prices, availability and images aligned wherever a customer discovers the catalogue.", related: ["api", "product-schema", "e-commerce-seo"] },
  { slug: "customer-journey", term: "Customer journey", category: "E-commerce", definition: "A customer journey describes the stages someone moves through from first awareness to purchase and what happens afterwards.", whyItMatters: "Understanding the wider journey helps a store fix the right problem instead of polishing one screen while the surrounding experience remains uncertain.", related: ["user-journey", "product-page", "checkout"] },
  { slug: "ppc", term: "PPC", category: "Digital Marketing", definition: "PPC, or pay-per-click advertising, is a model where an advertiser pays when someone clicks an advert.", whyItMatters: "PPC can put a relevant offer in front of people quickly, but it needs clear targeting, useful landing pages and measurement to be worthwhile.", related: ["google-ads", "paid-traffic", "conversion-tracking"] },
  { slug: "google-ads", term: "Google Ads", category: "Digital Marketing", definition: "Google Ads is Google’s advertising platform for reaching people across search results, partner sites, video and other placements.", whyItMatters: "It can support a launch or capture active demand, but advertising spend cannot compensate for a confusing offer or a weak destination page.", related: ["ppc", "landing-page", "paid-traffic"] },
  { slug: "content-marketing", term: "Content marketing", category: "Digital Marketing", definition: "Content marketing uses useful, relevant content to attract, help and build trust with a particular audience.", whyItMatters: "It gives a business a way to demonstrate how it thinks before asking someone to enquire. The content works best when it has a clear audience and job.", related: ["e-e-a-t", "search-intent", "lead-generation"], service: { label: "Explore content", href: "/services/content" } },
  { slug: "digital-pr", term: "Digital PR", category: "Digital Marketing", definition: "Digital PR is the work of creating and sharing credible stories, expertise or assets that earn attention and references online.", whyItMatters: "Useful coverage and mentions can build trust and help people discover a business. It is stronger when the story comes from something real rather than manufactured noise.", related: ["backlinks", "content-marketing", "lead-generation"], service: { label: "Explore Digital PR", href: "/services/digital-pr" } },
  { slug: "social-media-marketing", term: "Social media marketing", category: "Digital Marketing", definition: "Social media marketing uses social platforms to build awareness, relationships and action around a business.", whyItMatters: "The right platform and format depend on the audience and the business. Consistent, useful communication usually outperforms posting without a purpose.", related: ["content-marketing", "paid-traffic", "analytics"] },
  { slug: "remarketing", term: "Remarketing", category: "Digital Marketing", definition: "Remarketing shows follow-up messages or adverts to people who have already interacted with a business or website.", whyItMatters: "It can help a considered purchase stay visible, but it needs sensible frequency, clear consent and a message that adds something new.", related: ["paid-traffic", "conversion-tracking", "analytics"] },
  { slug: "paid-traffic", term: "Paid traffic", category: "Digital Marketing", definition: "Paid traffic is the visitors a website receives through purchased advertising placements.", whyItMatters: "Paid visits can be useful for testing an offer or reaching a defined audience, but they should be judged by the quality of the resulting journey, not clicks alone.", related: ["ppc", "google-ads", "conversion-rate"] },
  { slug: "conversion-tracking", term: "Conversion tracking", category: "Digital Marketing", definition: "Conversion tracking records when someone completes a valuable action, such as submitting a form, calling or buying.", whyItMatters: "Without reliable tracking, marketing decisions become guesswork. Tracking should respect privacy and measure actions that matter to the business.", related: ["analytics", "attribution", "conversion-rate-optimisation"] },
  { slug: "analytics", term: "Analytics", category: "Digital Marketing", definition: "Analytics is the collection and interpretation of information about how people find and use a website or campaign.", whyItMatters: "Good analytics helps a team ask better questions about behaviour and outcomes. It should inform judgement, not replace it with a dashboard of vanity numbers.", related: ["conversion-tracking", "attribution", "conversion-rate"] },
  { slug: "attribution", term: "Attribution", category: "Digital Marketing", definition: "Attribution is the method used to understand which interactions may have contributed to a conversion.", whyItMatters: "People often use several channels before making a decision. Attribution can add context, but no model perfectly explains a human journey.", related: ["analytics", "conversion-tracking", "customer-journey"] },
  { slug: "lead-generation", term: "Lead generation", category: "Digital Marketing", definition: "Lead generation is the process of attracting and capturing interest from potential customers.", whyItMatters: "The quality of a lead matters as much as the quantity. Clear positioning, useful content and a low-friction next step help the right people raise their hand.", related: ["cta", "conversion-rate-optimisation", "content-marketing"], service: { label: "Explore web design", href: "/services/web-design" } },
]

export const glossaryBySlug = new Map(glossaryTerms.map((term) => [term.slug, term]))

export function getGlossaryTerm(slug: string) {
  return glossaryBySlug.get(slug)
}

export function getRelatedTerms(slugs: string[]) {
  return slugs.map((slug) => glossaryBySlug.get(slug)).filter((term): term is GlossaryTerm => Boolean(term))
}
