export type Location = {
  slug: string
  name: string
  region: string
  descriptor: string
  intro: string
  localContext: string
  audience?: string
  approach?: string
  localHeading?: string
  commercialDetail?: string
  faq?: { question: string; answer: string }[]
  image: string
  imageAlt: string
  nearby: string[]
  focus: string[]
}

export const locations: Location[] = [
  { slug: "north-devon", name: "North Devon", region: "Devon", descriptor: "Web design in North Devon for ambitious local businesses.", intro: "A strategic web design partner for businesses across North Devon, from Barnstaple and Bideford to Ilfracombe, South Molton and the coast.", localContext: "North Devon is a place of independent businesses, tourism, professional services, food, agriculture, construction and creative work. A strong website needs to feel rooted in the area while making the business easy to choose for customers near and far.", audience: "We support North Devon businesses at different stages: a new business building credibility, an established company whose website no longer reflects its expertise, or a growing team that needs better content, clearer journeys and a more reliable digital platform.", approach: "We start with the business rather than a template. We clarify what you offer, who needs it, what makes you different and what a visitor should do next. From there we shape the content, design and development into one coherent experience.", localHeading: "A stronger digital presence for North Devon businesses.", commercialDetail: "North Devon businesses often serve a mix of local customers, visitors, referral networks and national buyers. That means a good website has to balance local relevance with enough confidence to compete beyond the region. We build clear service journeys, useful local signals and content that gives every audience a reason to take the next step.", faq: [{ question: "Which areas of North Devon do you cover?", answer: "We work with businesses in Barnstaple, Bideford, Ilfracombe, South Molton, Braunton, Croyde and surrounding North Devon communities." }, { question: "Can you help an existing North Devon business improve its website?", answer: "Yes. A redesign can improve clarity, enquiries, search visibility, performance and the ease of updating the site without discarding what already works." }], image: "/images/barnstaple-reflected-in-water.webp", imageAlt: "Barnstaple riverside reflected in the water", nearby: ["Barnstaple", "Bideford", "Ilfracombe"], focus: ["Web design", "Website development", "Local SEO"] },
  { slug: "barnstaple", name: "Barnstaple", region: "North Devon", descriptor: "Web design in Barnstaple for businesses across North Devon.", intro: "A considered digital partner for Barnstaple businesses that want to look credible, communicate clearly and turn more of the right visits into conversations.", localContext: "From our North Devon home base, we understand the character of Barnstaple’s independent businesses, professional services, hospitality and growing creative community.", audience: "We work with independent businesses, professional services, makers, hospitality teams and growing organisations that need their website to do more than sit online. It needs to explain the offer, build trust with the right local audience and create a clear route to enquire.", approach: "Our approach combines local understanding with the standards expected of a modern business website: useful content, confident design, accessible development, fast performance and a search structure that helps people find the right page.", localHeading: "Web design rooted in Barnstaple, built for growth across North Devon.", commercialDetail: "Whether you are based in the town centre, trading from an industrial estate or serving customers across the wider North Devon area, your website should make your expertise easy to understand. We can help with web design, website development, e-commerce, local SEO and ongoing improvement.", faq: [{ question: "How much does web design in Barnstaple cost?", answer: "The right investment depends on the scope, content and functionality your business needs. We shape recommendations around your goals rather than forcing every Barnstaple business into the same package." }, { question: "Do you only work with businesses in Barnstaple?", answer: "No. Barnstaple is our North Devon base, and we work with businesses across Devon and remotely throughout the UK." }], image: "/images/barnstaple-reflected-in-water.webp", imageAlt: "Barnstaple riverside reflected in the water", nearby: ["North Devon", "South Molton", "Ilfracombe"], focus: ["Web design", "Website development", "Local SEO"] },
  { slug: "bideford", name: "Bideford", region: "North Devon", descriptor: "Web design for businesses in Bideford and across the Torridge coast.", intro: "Websites with the clarity and character Bideford businesses need to compete locally, reach beyond the town and make a stronger first impression.", localContext: "Bideford’s waterfront, independent businesses and surrounding communities need digital experiences that feel personal, useful and easy to act on.", localHeading: "Digital clarity for Bideford and the Torridge coast.", commercialDetail: "From Bideford’s independent shops and hospitality businesses to trades, professional services and coastal organisations, we create websites that balance character with conversion. Your site can be distinctive without making visitors work to understand what you do, where you serve and how to contact you.", faq: [{ question: "Do you provide web design for Bideford businesses?", answer: "Yes. We work with Bideford businesses and organisations across Torridge on web design, development, e-commerce and SEO projects." }, { question: "Can a Bideford website reach customers outside North Devon?", answer: "Absolutely. Strong local positioning can sit alongside broader service content, helping you be relevant to nearby customers while presenting your business confidently further afield." }], image: "/images/bideford-waterfront.png", imageAlt: "Bideford waterfront and historic bridge", nearby: ["Torridge", "Westward Ho!", "Appledore"], focus: ["Web design", "E-commerce", "SEO"] },
  { slug: "exeter", name: "Exeter", region: "Devon", descriptor: "Strategic web design in Exeter for businesses ready to grow.", intro: "A sharper website for Exeter organisations that need to explain a complex offer, stand apart in a competitive market and generate better enquiries.", localContext: "Exeter combines ambitious independent businesses, professional services, education and technology. Your website should reflect the confidence of the city you operate in.", localHeading: "Web design in Exeter for businesses with something to explain.", commercialDetail: "In a competitive Exeter market, surface-level polish is not enough. We help organisations turn complex services into clear journeys, support credibility with useful evidence and make it easier for prospective clients to compare, understand and enquire.", faq: [{ question: "Can a North Devon studio work with an Exeter business?", answer: "Yes. We work remotely and collaboratively with Exeter businesses, bringing the same strategic process, responsive communication and technical standards to every project." }, { question: "Do you build websites for professional services in Exeter?", answer: "Yes. Clear positioning, structured content, case studies and thoughtful enquiry journeys are especially valuable for professional and technical businesses." }], image: "/images/exeter-aerial-view.jpeg", imageAlt: "Aerial view of Exeter and the River Exe", nearby: ["East Devon", "Exmouth", "Crediton"], focus: ["Web design", "Website redesign", "Technical SEO"] },
  { slug: "plymouth", name: "Plymouth", region: "South Devon", descriptor: "High-performance web design for Plymouth businesses.", intro: "Digital experiences that help Plymouth businesses make their value obvious, build trust quickly and reach customers across the city and beyond.", localContext: "Plymouth is a city of makers, marine businesses, hospitality, professional services and ambitious independents. We shape websites around the audience and the opportunity.", localHeading: "A practical digital platform for Plymouth businesses.", commercialDetail: "Plymouth businesses often need to communicate expertise across a wide geography. We combine clear messaging, strong visual systems and search foundations so your website can attract local customers, support referrals and create a credible route into larger opportunities.", faq: [{ question: "What kind of Plymouth businesses do you work with?", answer: "We work with independent businesses, professional services, e-commerce brands, makers and organisations that need a clearer, more effective website." }, { question: "Can you improve an underperforming Plymouth website?", answer: "Yes. We can audit the structure, content, user journeys and technical performance before recommending the most valuable improvements." }], image: "/images/plymouth-hoe-aerial.jpeg", imageAlt: "Plymouth Hoe and coastline from above", nearby: ["South Devon", "Ivybridge", "Saltash"], focus: ["Web design", "E-commerce", "Content"] },
  { slug: "torquay", name: "Torquay", region: "South Devon", descriptor: "Web design for Torquay and English Riviera businesses.", intro: "Memorable, conversion-focused websites for Torquay businesses in hospitality, tourism, retail and professional services.", localContext: "In a destination market, your website has to create confidence before someone arrives. We combine strong visual direction with clear journeys and useful content.", localHeading: "Web design for Torquay businesses that compete on experience.", commercialDetail: "For tourism, hospitality, retail and local services in Torquay, the website is often the first part of the experience. We help businesses show the quality of what they offer, answer practical questions, build trust and make booking, buying or enquiring feel straightforward.", faq: [{ question: "Can you help Torquay tourism and hospitality businesses?", answer: "Yes. We design content-led websites for businesses that need to communicate an experience clearly before a visitor arrives." }, { question: "Is local SEO useful for a Torquay business?", answer: "Local SEO can help people discover relevant services and experiences, especially when useful location, service and visitor information is built into the site naturally." }], image: "/images/torquay-harbor.jpeg", imageAlt: "Torquay harbour and waterfront", nearby: ["English Riviera", "Paignton", "Newton Abbot"], focus: ["Web design", "Website redesign", "Local SEO"] },
]

export const getLocation = (slug: string) => locations.find((location) => location.slug === slug)
export const locationSlugs = locations.map((location) => location.slug)
