export type Location = {
  slug: string
  name: string
  region: string
  descriptor: string
  intro: string
  localContext: string
  audience?: string
  approach?: string
  image: string
  imageAlt: string
  nearby: string[]
  focus: string[]
}

export const locations: Location[] = [
  { slug: "north-devon", name: "North Devon", region: "Devon", descriptor: "Web design in North Devon for ambitious local businesses.", intro: "A strategic web design partner for businesses across North Devon, from Barnstaple and Bideford to Ilfracombe, South Molton and the coast.", localContext: "North Devon is a place of independent businesses, tourism, professional services, food, agriculture, construction and creative work. A strong website needs to feel rooted in the area while making the business easy to choose for customers near and far.", audience: "We support North Devon businesses at different stages: a new business building credibility, an established company whose website no longer reflects its expertise, or a growing team that needs better content, clearer journeys and a more reliable digital platform.", approach: "We start with the business rather than a template. We clarify what you offer, who needs it, what makes you different and what a visitor should do next. From there we shape the content, design and development into one coherent experience.", image: "/images/barnstaple-reflected-in-water.webp", imageAlt: "Barnstaple riverside reflected in the water", nearby: ["Barnstaple", "Bideford", "Ilfracombe"], focus: ["Web design", "Website development", "Local SEO"] },
  { slug: "barnstaple", name: "Barnstaple", region: "North Devon", descriptor: "Web design in Barnstaple for businesses across North Devon.", intro: "A considered digital partner for Barnstaple businesses that want to look credible, communicate clearly and turn more of the right visits into conversations.", localContext: "From our North Devon home base, we understand the character of Barnstaple’s independent businesses, professional services, hospitality and growing creative community.", audience: "We work with independent businesses, professional services, makers, hospitality teams and growing organisations that need their website to do more than sit online. It needs to explain the offer, build trust with the right local audience and create a clear route to enquire.", approach: "Our approach combines local understanding with the standards expected of a modern business website: useful content, confident design, accessible development, fast performance and a search structure that helps people find the right page.", image: "/images/barnstaple-reflected-in-water.webp", imageAlt: "Barnstaple riverside reflected in the water", nearby: ["North Devon", "South Molton", "Ilfracombe"], focus: ["Web design", "Website development", "Local SEO"] },
  { slug: "bideford", name: "Bideford", region: "North Devon", descriptor: "Web design for businesses in Bideford and across the Torridge coast.", intro: "Websites with the clarity and character Bideford businesses need to compete locally, reach beyond the town and make a stronger first impression.", localContext: "Bideford’s waterfront, independent businesses and surrounding communities need digital experiences that feel personal, useful and easy to act on.", image: "/images/bideford-waterfront.png", imageAlt: "Bideford waterfront and historic bridge", nearby: ["Torridge", "Westward Ho!", "Appledore"], focus: ["Web design", "E-commerce", "SEO"] },
  { slug: "exeter", name: "Exeter", region: "Devon", descriptor: "Strategic web design in Exeter for businesses ready to grow.", intro: "A sharper website for Exeter organisations that need to explain a complex offer, stand apart in a competitive market and generate better enquiries.", localContext: "Exeter combines ambitious independent businesses, professional services, education and technology. Your website should reflect the confidence of the city you operate in.", image: "/images/exeter-aerial-view.jpeg", imageAlt: "Aerial view of Exeter and the River Exe", nearby: ["East Devon", "Exmouth", "Crediton"], focus: ["Web design", "Website redesign", "Technical SEO"] },
  { slug: "plymouth", name: "Plymouth", region: "South Devon", descriptor: "High-performance web design for Plymouth businesses.", intro: "Digital experiences that help Plymouth businesses make their value obvious, build trust quickly and reach customers across the city and beyond.", localContext: "Plymouth is a city of makers, marine businesses, hospitality, professional services and ambitious independents. We shape websites around the audience and the opportunity.", image: "/images/plymouth-hoe-aerial.jpeg", imageAlt: "Plymouth Hoe and coastline from above", nearby: ["South Devon", "Ivybridge", "Saltash"], focus: ["Web design", "E-commerce", "Content"] },
  { slug: "torquay", name: "Torquay", region: "South Devon", descriptor: "Web design for Torquay and English Riviera businesses.", intro: "Memorable, conversion-focused websites for Torquay businesses in hospitality, tourism, retail and professional services.", localContext: "In a destination market, your website has to create confidence before someone arrives. We combine strong visual direction with clear journeys and useful content.", image: "/images/torquay-harbor.jpeg", imageAlt: "Torquay harbour and waterfront", nearby: ["English Riviera", "Paignton", "Newton Abbot"], focus: ["Web design", "Website redesign", "Local SEO"] },
]

export const getLocation = (slug: string) => locations.find((location) => location.slug === slug)
export const locationSlugs = locations.map((location) => location.slug)
