export type Service = {
  slug: string
  group: "Websites" | "Growth" | "Ongoing"
  eyebrow: string
  title: string
  shortTitle: string
  description: string
  problem: string
  approach: { title: string; text: string }[]
  included: string[]
  related: string[]
  faqs: { question: string; answer: string }[]
  image: string
  alt: string
}

export const serviceGroups = [
  { number: "01", name: "Websites", title: "Websites that look brilliant. And work hard.", intro: "Strategy, UX, design and development in one connected process — so the final website is as useful as it is distinctive." },
  { number: "02", name: "Growth", title: "Getting the right people to your website.", intro: "Search, content and technical improvements that help good businesses become easier to find and easier to choose." },
  { number: "03", name: "Ongoing", title: "Good websites should keep getting better.", intro: "Practical support and continuous optimisation for the site you rely on every day." },
] as const

export const services: Service[] = [
  { slug: "web-design", group: "Websites", eyebrow: "Web design", title: "Web design that gives your business an unfair advantage.", shortTitle: "Web design", description: "A clear, considered digital presence that makes the right first impression and gives people a reason to stay.", problem: "Your website is often the first impression someone has of your business. If it looks dated, feels difficult to use or fails to communicate what makes you different, you are already losing people.", approach: [{ title: "Discover", text: "We get close to the business, the audience and the opportunity before touching the interface." }, { title: "Shape", text: "We turn the raw material into a sharper story, clearer structure and a useful route through the site." }, { title: "Design", text: "We create a visual system with enough character to be remembered and enough clarity to work." }, { title: "Launch", text: "We build, test and release a site that is ready for real people, real devices and real decisions." }], included: ["Sitemap and content structure", "UX direction and wireframes", "Responsive interface design", "Accessible component system", "CMS-ready page templates", "Launch support and handover"], related: ["website-development", "website-redesign", "seo"], faqs: [{ question: "How long does a website project take?", answer: "Most focused projects take between six and twelve weeks, depending on the number of templates, content readiness and review stages." }, { question: "Can you work with our existing brand?", answer: "Yes. We can work within an established identity, evolve it where needed, or create a more complete digital direction around it." }], image: "/images/responsive-showcase.png", alt: "Responsive website layouts on different screens" },
  { slug: "website-development", group: "Websites", eyebrow: "Website development", title: "A website built properly behind the scenes.", shortTitle: "Website development", description: "Fast, accessible and maintainable development that turns a good idea into a dependable digital product.", problem: "A beautiful design is only useful when the technology underneath it is stable, fast and easy to evolve. Many websites become expensive to change because they were built around shortcuts.", approach: [{ title: "Plan", text: "We choose the right structure, platform and content model for the job — not the trend of the month." }, { title: "Build", text: "We develop responsive, accessible interfaces with clean components and sensible technical foundations." }, { title: "Test", text: "We check the important things: speed, keyboard access, mobile behaviour, forms and search visibility." }, { title: "Improve", text: "We leave you with a site that can grow without starting again from scratch." }], included: ["Next.js or platform-led builds", "Responsive front-end development", "CMS and integrations", "Performance and accessibility checks", "Analytics and conversion setup", "Technical handover"], related: ["web-design", "ecommerce", "technical-seo"], faqs: [{ question: "Can you improve an existing website?", answer: "Yes. We can work within an existing codebase or platform when that is the most sensible route." }, { question: "Will the website be easy to update?", answer: "We design the content structure and editing experience around the people who will actually manage it." }], image: "/images/responsive-showcase.png", alt: "Responsive digital experience across devices" },
  { slug: "ecommerce", group: "Websites", eyebrow: "E-commerce", title: "An online shop that makes buying feel simple.", shortTitle: "E-commerce", description: "Thoughtful storefronts and customer journeys that reduce friction from first click to final order.", problem: "People abandon online shops when the experience feels uncertain, slow or harder than it needs to be. The best e-commerce work removes doubt at every step.", approach: [{ title: "Understand", text: "We map products, customers and fulfilment so the store reflects how the business really works." }, { title: "Simplify", text: "We make browsing, comparing and buying feel obvious across mobile and desktop." }, { title: "Connect", text: "We connect the storefront to the tools that keep orders, stock and customer information moving." }, { title: "Optimise", text: "We use evidence from behaviour and performance to keep improving the journey." }], included: ["Storefront strategy and UX", "Product and collection architecture", "Shopify or platform integration", "Cart and checkout journey", "Payment and fulfilment integrations", "Conversion-focused analytics"], related: ["web-design", "website-development", "seo"], faqs: [{ question: "Which e-commerce platforms do you use?", answer: "We choose the platform around your catalogue, fulfilment needs and growth plans. Shopify is often a strong fit, but it is not the only option." }, { question: "Can you redesign an existing store?", answer: "Yes. We can improve the customer journey, storefront design and conversion points without losing the operational parts that already work." }], image: "/images/responsive-showcase.png", alt: "E-commerce storefront displayed on responsive screens" },
  { slug: "website-redesign", group: "Websites", eyebrow: "Website redesign", title: "A better website for the next chapter.", shortTitle: "Website redesign", description: "A sharper structure, stronger story and more useful experience for a business that has moved on.", problem: "Businesses change faster than their websites. A redesign is not about making every page look newer; it is about making the digital experience fit where you are going.", approach: [{ title: "Audit", text: "We look at what is working, what is getting in the way and what your users are trying to do." }, { title: "Prioritise", text: "We focus the redesign on the pages, journeys and messages that can make the biggest difference." }, { title: "Reframe", text: "We bring the content, structure and visual language into the same conversation." }, { title: "Migrate", text: "We protect the useful parts of the existing site while giving the experience a clearer future." }], included: ["Website and content audit", "Information architecture", "UX and visual redesign", "Content migration plan", "SEO-safe redirects", "Launch and post-launch support"], related: ["web-design", "website-development", "seo"], faqs: [{ question: "Will a redesign affect our SEO?", answer: "We plan redirects, metadata and content structure carefully so the redesign protects existing value and creates room to grow." }, { question: "Do we need new content?", answer: "Not always. We can work with what you have, identify the gaps and help shape the most important new content." }], image: "/images/barnstaple-reflected-in-water.webp", alt: "Barnstaple waterfront reflected in water" },
  { slug: "seo", group: "Growth", eyebrow: "SEO", title: "SEO that makes your good work easier to find.", shortTitle: "SEO", description: "A practical search strategy built around the people you want to reach and the decisions you need them to make.", problem: "Being good at what you do is not enough if the right people cannot find you. Search visibility comes from useful content, technical confidence and consistency over time.", approach: [{ title: "Research", text: "We understand the language, intent and competitive landscape around your most valuable opportunities." }, { title: "Fix", text: "We remove technical and structural barriers that make it harder for search engines and people to understand the site." }, { title: "Create", text: "We shape useful pages and content that answer real questions rather than filling space with keywords." }, { title: "Learn", text: "We measure what is changing and focus effort where it can compound." }], included: ["Search opportunity research", "Technical SEO audit", "On-page optimisation", "Content planning", "Internal linking", "Monthly reporting and recommendations"], related: ["local-seo", "technical-seo", "content", "web-design"], faqs: [{ question: "How quickly will SEO work?", answer: "Some technical improvements can help quickly, while authority and content gains usually build over several months. We set expectations around the opportunity, not a guarantee." }, { question: "Do you guarantee rankings?", answer: "No. Search results depend on many factors outside anyone’s control. We do guarantee a clear plan, careful work and honest reporting." }], image: "/images/exeter-aerial-view.jpeg", alt: "Aerial view of Exeter and surrounding landscape" },
  { slug: "local-seo", group: "Growth", eyebrow: "Local SEO", title: "Be easier to choose in your local market.", shortTitle: "Local SEO", description: "A grounded local search strategy for businesses that need to be visible where their customers actually are.", problem: "Local customers often choose between a handful of businesses. If your information is inconsistent or your value is unclear, you may never make the shortlist.", approach: [{ title: "Map", text: "We identify the places, services and questions that matter in your local market." }, { title: "Clarify", text: "We make your business information consistent and your service pages genuinely useful." }, { title: "Prove", text: "We connect local relevance to real projects, reviews and evidence — not empty location pages." }], included: ["Google Business Profile guidance", "Local landing page strategy", "Citation and consistency checks", "Review and reputation prompts", "Local content opportunities", "Performance tracking"], related: ["seo", "content", "web-design"], faqs: [{ question: "Do you create lots of location pages?", answer: "No. We prefer a smaller number of useful pages with genuine local relevance over thin doorway pages." }, { question: "Can you help a Devon business compete beyond Devon?", answer: "Yes. Local relevance can support a wider strategy when the site also clearly communicates what makes the business different." }], image: "/images/bideford-waterfront.png", alt: "Bideford waterfront in North Devon" },
  { slug: "technical-seo", group: "Growth", eyebrow: "Technical SEO", title: "A stronger technical foundation for search and people.", shortTitle: "Technical SEO", description: "The less visible work that helps a website load, make sense and perform with confidence.", problem: "Technical problems rarely announce themselves. They show up as slow pages, confused crawlers, poor mobile experiences and missed opportunities.", approach: [{ title: "Inspect", text: "We review crawlability, indexing, performance, structure and the signals that shape the experience." }, { title: "Prioritise", text: "We separate urgent blockers from useful improvements so the work stays commercially focused." }, { title: "Resolve", text: "We work with your team or development partner to implement and verify the changes." }], included: ["Crawl and indexation review", "Core Web Vitals guidance", "Metadata and structured data", "Redirect and canonical checks", "Sitemap and robots review", "Technical implementation support"], related: ["seo", "website-development", "website-redesign"], faqs: [{ question: "Do you need access to our website?", answer: "Read-only access is often enough for an audit. Implementation may need collaboration with whoever manages your website or hosting." }, { question: "Is technical SEO only for large websites?", answer: "No. Small websites benefit too — especially when a few structural issues are blocking otherwise good content." }], image: "/images/torquay-harbor.jpeg", alt: "Torquay harbour on the Devon coast" },
  { slug: "content", group: "Growth", eyebrow: "Content", title: "Content with a job to do.", shortTitle: "Content", description: "Clearer words, better page structure and useful ideas that help people understand and trust the business.", problem: "When content is vague, overstuffed or written without a reader in mind, even a beautiful website feels difficult to choose.", approach: [{ title: "Listen", text: "We learn the language your customers use and the detail that makes your expertise credible." }, { title: "Structure", text: "We give each page a clear purpose, hierarchy and next step." }, { title: "Write", text: "We make the message direct, distinctive and useful without flattening the human side of the business." }], included: ["Website copy direction", "Service page copy", "SEO-aware content planning", "Case study structure", "Editorial review", "Content governance guidance"], related: ["seo", "local-seo", "web-design"], faqs: [{ question: "Can you write the content as well as design the site?", answer: "Yes. Content and design work better when they are shaped together, especially on the pages that drive enquiries." }, { question: "Do you work with subject matter experts?", answer: "Absolutely. The best content usually combines your specialist knowledge with our structure, editing and audience perspective." }], image: "/images/plymouth-hoe-aerial.jpeg", alt: "Aerial view of Plymouth Hoe and coastline" },
  { slug: "digital-pr", group: "Growth", eyebrow: "Digital PR & authority", title: "Build the kind of authority people can feel.", shortTitle: "Digital PR", description: "Useful stories, credible mentions and stronger signals around the work you already do.", problem: "Authority is not something you can manufacture with a badge. It is built when the right people can see evidence that your business understands its subject.", approach: [{ title: "Find the story", text: "We look for the useful, interesting or locally relevant angles already inside the business." }, { title: "Make it useful", text: "We turn expertise into assets and ideas that other people can genuinely reference." }, { title: "Put it out there", text: "We help shape outreach and partnerships that build relevance without empty noise." }], included: ["Authority opportunity research", "Digital PR ideas", "Expert commentary angles", "Link-worthy content assets", "Outreach direction", "Authority reporting"], related: ["seo", "content", "local-seo"], faqs: [{ question: "Do you promise a certain number of links?", answer: "No. We focus on relevance and quality rather than chasing a number that may not help the business." }, { question: "Is digital PR only for national brands?", answer: "No. Local expertise, useful data and strong stories can create authority for businesses of any size." }], image: "/images/barnstaple-reflected-in-water.webp", alt: "Barnstaple reflected in the River Taw" },
  { slug: "website-maintenance", group: "Ongoing", eyebrow: "Website maintenance", title: "A website that stays useful after launch.", shortTitle: "Website maintenance", description: "Reliable updates, considered improvements and a calm technical partner for the site you rely on.", problem: "A website is not finished when it launches. Content changes, software updates, new questions and small issues all arrive afterwards.", approach: [{ title: "Monitor", text: "We keep an eye on the important signals: uptime, updates, forms, security and performance." }, { title: "Maintain", text: "We handle the practical changes that keep the site stable and accurate." }, { title: "Improve", text: "We use the ongoing relationship to make small, valuable improvements before they become bigger jobs." }], included: ["Platform and dependency updates", "Content and layout changes", "Broken link and form checks", "Security and backup guidance", "Performance monitoring", "Priority support options"], related: ["seo", "technical-seo", "website-development"], faqs: [{ question: "Can you maintain a website you did not build?", answer: "Usually, yes. We start with a short technical review so we understand the platform and any risks before taking responsibility." }, { question: "Do you offer fixed monthly support?", answer: "Yes. Support can be structured around a monthly allocation or a more focused maintenance arrangement." }], image: "/images/responsive-showcase.png", alt: "Responsive website interface on multiple devices" },
]

export const getService = (slug: string) => services.find((service) => service.slug === slug)

export const serviceSlugs = services.map((service) => service.slug)

export const groupServices = (group: Service["group"]) => services.filter((service) => service.group === group)
