import type { Metadata } from "next"
import Link from "next/link"
import { notFound } from "next/navigation"
import { ArrowDown, ArrowUpRight, Check } from "lucide-react"
import { getService, serviceSlugs } from "@/lib/services"

export function generateStaticParams() { return serviceSlugs.map((slug) => ({ slug })) }

export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> {
  const { slug } = await params
  const service = getService(slug)
  if (!service) return {}
  return { title: service.shortTitle, description: service.description, alternates: { canonical: `/services/${service.slug}` }, openGraph: { title: `${service.shortTitle} | Dream Pixel`, description: service.description, type: "website" } }
}

export default async function ServiceDetailPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params
  const service = getService(slug)
  if (!service) notFound()
  return <main className="overflow-hidden bg-background">
    <section className="relative overflow-hidden bg-foreground px-6 py-24 text-background md:px-12 md:py-32"><div className="pointer-events-none absolute right-[-15%] top-[-20%] size-[65vw] rounded-full border border-primary/25" /><div className="container relative z-10"><div className="mb-10 flex flex-wrap items-center gap-x-6 gap-y-3 font-mono text-xs uppercase tracking-[.25em] text-accent"><Link href="/services" className="transition hover:text-background">Services</Link><span>/</span><span>{service.eyebrow}</span></div><h1 className="max-w-6xl font-display text-6xl font-black leading-[.86] tracking-[-.07em] md:text-8xl lg:text-[9.5rem]">{service.title}</h1><div className="mt-12 grid gap-10 border-t border-background/20 pt-6 lg:grid-cols-[1fr_auto]"><p className="max-w-2xl text-lg leading-relaxed text-background/70 md:text-xl">{service.description}</p><div className="flex flex-wrap items-start gap-3"><Link href="/contact" className="inline-flex items-center gap-3 bg-primary px-5 py-4 font-mono text-xs uppercase tracking-[.18em] text-primary-foreground transition hover:bg-accent">Start a project <ArrowUpRight className="size-4" /></Link><Link href="/portfolio" className="inline-flex items-center gap-3 border border-background/30 px-5 py-4 font-mono text-xs uppercase tracking-[.18em] transition hover:border-background hover:bg-background hover:text-foreground">View our work</Link></div></div><div className="mt-16 grid grid-cols-2 gap-px bg-background/20 sm:grid-cols-4">{["Strategy", "Structure", "Execution", "Improvement"].map((item, index) => <div key={item} className="bg-foreground p-4"><span className="font-mono text-xs text-primary">0{index + 1}</span><p className="mt-8 font-display text-lg font-bold">{item}</p></div>)}</div></div></section>
    <section className="bg-background px-6 py-24 md:px-12 md:py-36"><div className="container grid gap-14 lg:grid-cols-[.8fr_1.2fr]"><div><p className="mb-5 font-mono text-xs uppercase tracking-[.3em] text-primary">The problem</p><h2 className="max-w-xl font-display text-5xl font-black leading-[.9] tracking-[-.06em] md:text-7xl">Make the next decision easier.</h2></div><p className="max-w-2xl self-end text-2xl leading-relaxed text-muted-foreground md:text-3xl">{service.problem}</p></div></section>
    <section className="bg-card px-6 py-24 md:px-12 md:py-36"><div className="container grid gap-16 lg:grid-cols-[.7fr_1.3fr]"><div><p className="mb-5 font-mono text-xs uppercase tracking-[.3em] text-accent">The approach</p><h2 className="font-display text-5xl font-black leading-[.9] tracking-[-.06em] md:text-7xl">How we move<br /><span className="text-primary">from thought to useful.</span></h2></div><div className="flex flex-col">{service.approach.map((step, index) => <article key={step.title} className="grid gap-5 border-t border-border py-7 md:grid-cols-[5rem_1fr]"><span className="font-mono text-sm text-primary">0{index + 1}</span><div><h3 className="font-display text-3xl font-bold tracking-[-.04em]">{step.title}</h3><p className="mt-3 max-w-xl leading-relaxed text-muted-foreground">{step.text}</p></div></article>)}</div></div></section>
    <section className="bg-background px-6 py-24 md:px-12 md:py-36"><div className="container grid gap-14 lg:grid-cols-[.75fr_1.25fr]"><div><p className="mb-5 font-mono text-xs uppercase tracking-[.3em] text-primary">What&apos;s included</p><h2 className="font-display text-5xl font-black leading-[.9] tracking-[-.06em] md:text-7xl">Useful by<br />design.</h2></div><div className="grid gap-px bg-border sm:grid-cols-2">{service.included.map((item) => <div key={item} className="flex min-h-24 items-start gap-3 bg-background p-5"><Check className="mt-1 size-4 shrink-0 text-accent" /><span className="leading-relaxed">{item}</span></div>)}</div></div></section>
    <section className="bg-primary px-6 py-24 text-primary-foreground md:px-12 md:py-32"><div className="container grid gap-12 lg:grid-cols-[1fr_.8fr] lg:items-end"><div><p className="mb-5 font-mono text-xs uppercase tracking-[.3em] text-primary-foreground/70">Dream Pixel / {service.eyebrow}</p><h2 className="max-w-4xl font-display text-5xl font-black leading-[.9] tracking-[-.06em] md:text-8xl">Better work starts with a better question.</h2></div><div className="flex flex-col gap-4"><p className="leading-relaxed text-primary-foreground/80">We keep the work close to the real business: what people need, what the team can manage and what should happen next.</p><Link href="/contact" className="inline-flex w-fit items-center gap-3 border border-primary-foreground/40 px-6 py-4 font-mono text-xs uppercase tracking-[.18em] transition hover:bg-primary-foreground hover:text-primary">Start a project <ArrowUpRight className="size-5" /></Link></div></div></section>
    <section className="bg-background px-6 py-24 md:px-12 md:py-36"><div className="container grid gap-14 lg:grid-cols-[.75fr_1.25fr]"><div><p className="mb-5 font-mono text-xs uppercase tracking-[.3em] text-accent">Common questions</p><h2 className="font-display text-5xl font-black leading-[.9] tracking-[-.06em] md:text-7xl">Before we<br />get started.</h2></div><div className="flex flex-col">{service.faqs.map((faq) => <details key={faq.question} className="group border-t border-border py-6"><summary className="flex cursor-pointer list-none items-center justify-between gap-6 font-display text-2xl font-bold tracking-[-.03em] [&::-webkit-details-marker]:hidden">{faq.question}<span className="font-mono text-primary transition group-open:rotate-45">+</span></summary><p className="max-w-2xl pt-4 leading-relaxed text-muted-foreground">{faq.answer}</p></details>)}</div></div></section>
    <section className="bg-foreground px-6 py-24 text-background md:px-12 md:py-32"><div className="container flex flex-col justify-between gap-10 md:flex-row md:items-end"><div><p className="mb-5 font-mono text-xs uppercase tracking-[.3em] text-accent">Next chapter</p><h2 className="max-w-4xl font-display text-5xl font-black leading-[.9] tracking-[-.06em] md:text-8xl">Ready to build something better?</h2></div><Link href="/contact" className="inline-flex items-center gap-3 bg-primary px-6 py-4 font-mono text-xs uppercase tracking-[.18em] text-primary-foreground transition hover:bg-accent">Start a project <ArrowUpRight className="size-5" /></Link></div></section>
  </main>
}
